# Generated by Django 6.0.6 on 2026-07-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya', models.CharField(max_length=100, unique=True, verbose_name='الولاية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر التوصيل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('estimated_days', models.IntegerField(default=3, verbose_name='أيام التوصيل المقدرة')),
            ],
            options={
                'verbose_name': 'أسعار التوصيل',
                'ordering': ['wilaya'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='رواق المسلم', max_length=200, verbose_name='اسم المتجر')),
                ('store_subtitle', models.CharField(blank=True, default='متجر الملابس والكتب الإسلامية', max_length=300, verbose_name='وصف المتجر')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='اللوقو')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='أيقونة المتصفح')),
                ('primary_color', models.CharField(default='#1a5632', max_length=20, verbose_name='اللون الرئيسي')),
                ('secondary_color', models.CharField(default='#c8a951', max_length=20, verbose_name='اللون الثانوي')),
                ('accent_color', models.CharField(default='#dc3545', max_length=20, verbose_name='لون التمييز')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('tiktok', models.URLField(blank=True, verbose_name='TikTok')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('hero_title', models.CharField(blank=True, default='رواق المسلم', max_length=200, verbose_name='عنوان الرئيسية')),
                ('hero_subtitle', models.CharField(blank=True, default='أفضل الملابس والكتب الإسلامية بجودة عالية', max_length=300, verbose_name='وصف الرئيسية')),
                ('hero_button_text', models.CharField(blank=True, default='تسوق الآن', max_length=50, verbose_name='نص زر الرئيسية')),
                ('footer_text', models.CharField(blank=True, default='جميع الحقوق محفوظة', max_length=300, verbose_name='نص الفوتر')),
                ('free_shipping_min', models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='الحد الأدنى للشحن المجاني')),
                ('default_shipping_cost', models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='تكلفة الشحن الافتراضية')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة')),
                ('show_special_offers', models.BooleanField(default=True, verbose_name='عرض العروض الخاصة')),
                ('show_new_products', models.BooleanField(default=True, verbose_name='عرض المنتجات الجديدة')),
                ('products_per_page', models.IntegerField(default=20, verbose_name='عدد المنتجات في الصفحة')),
                ('whatsapp_float', models.BooleanField(default=True, verbose_name='زر WhatsApp عائم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='العنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='الوصف')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='الصورة (ديسكتوب)')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='slides/phones/', verbose_name='الصورة (موبايل)')),
                ('link', models.URLField(blank=True, verbose_name='رابط')),
                ('button_text', models.CharField(blank=True, default='تسوق الآن', max_length=50, verbose_name='نص الزر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
            ],
            options={
                'verbose_name': 'صور السلايدر',
                'ordering': ['order'],
            },
        ),
    ]
