# Generated by Django 6.0.6 on 2026-07-04 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='رقم هاتف ثاني')),
                ('wilaya', models.CharField(max_length=100, verbose_name='الولاية')),
                ('commune', models.CharField(max_length=100, verbose_name='البلدية')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'تم التأكيد'), ('shipped', 'تم الشحن'), ('delivered', 'تم التوصيل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('payment_method', models.CharField(choices=[('cod', 'الدفع عند الاستلام'), (' ccp', 'تحويل CCP'), ('baridi', 'باريدي موب')], default='cod', max_length=20, verbose_name='طريقة الدفع')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المجموع الفرعي')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الشحن')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المجموع الكلي')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='رقم التتبع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'طلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300, verbose_name='اسم المنتج')),
                ('product_image', models.CharField(blank=True, max_length=500, verbose_name='صورة المنتج')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('quantity', models.IntegerField(default=1, verbose_name='الكمية')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'عناصر الطلب',
            },
        ),
    ]
