# Generated by Django 6.0.6 on 2026-07-04 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفئة')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='الرابط')),
                ('icon', models.CharField(blank=True, help_text='مثال: fas fa-book', max_length=100, verbose_name='أيقونة Font Awesome')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='الفئة الأب')),
            ],
            options={
                'verbose_name': 'فئات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='اسم المنتج')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='الرابط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر القديم')),
                ('image', models.ImageField(upload_to='products/main/', verbose_name='الصورة الرئيسية')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products/extra/', verbose_name='صورة ثانية')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products/extra/', verbose_name='صورة ثالثة')),
                ('is_new', models.BooleanField(default=True, verbose_name='جديد')),
                ('is_on_sale', models.BooleanField(default=False, verbose_name='عرض خاص')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('stock', models.IntegerField(default=0, verbose_name='المخزون')),
                ('views_count', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'منتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='الصورة')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='نص بديل')),
                ('order', models.IntegerField(default=0, verbose_name='ترتيب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صور المنتجات',
                'ordering': ['order'],
            },
        ),
    ]
